# Get all books

GET http://localhost:9080/Jakarta-Library-1.0-SNAPSHOT/api/books

###

# Get one book

GET http://localhost:9080/Jakarta-Library-1.0-SNAPSHOT/api/books/81fed01e-5b96-48ed-af1e-9b36afdec6bf

###

# Put new book

PUT http://localhost:9080/Jakarta-Library-1.0-SNAPSHOT/api/publishers/3b0a33fe-2d05-462c-bce7-032c0a542231/books/81fed01e-5b96-af1e-48ed-9b36afdec6bf
Content-Type: application/json

{
  "title": "testowa ksiazka",
  "author": "testowy autor",
  "state": "NEW"
}

###

# Get new book

GET http://localhost:9080/Jakarta-Library-1.0-SNAPSHOT/api/books/81fed01e-5b96-af1e-48ed-9b36afdec6bf

###

# Patch book

PATCH http://localhost:9080/Jakarta-Library-1.0-SNAPSHOT/api/books/81fed01e-5b96-af1e-48ed-9b36afdec6bf
Content-Type: application/json

{
  "title": "zmieniona ksiazka",
  "author": "zmieniony autor",
  "state": "USED"
}

###

# Delete Book

DELETE http://localhost:9080/Jakarta-Library-1.0-SNAPSHOT/api/books/9b377529-a869-41b2-bb05-58ebf3ea1756

###

# Get Publisher's book

GET http://localhost:9080/Jakarta-Library-1.0-SNAPSHOT/api/publishers/3b0a33fe-2d05-462c-bce7-032c0a542231/books

###

# Get all publishers

GET http://localhost:9080/Jakarta-Library-1.0-SNAPSHOT/api/publishers

###

# Get publisher

GET http://localhost:9080/Jakarta-Library-1.0-SNAPSHOT/api/publishers/3b0a33fe-2d05-462c-bce7-032c0a542231

###

# Create publisher

PUT http://localhost:9080/Jakarta-Library-1.0-SNAPSHOT/api/publishers/f8e63c10-5aaf-4b0d-a918-852c43855b4c
Content-Type: application/json

{
  "name": "Nowy Publisher",
  "country": "Polska",
  "dateOfCreation": "2024-10-30",
  "numOfWorkers": 3000
}

###

# Modify Publisher

PATCH http://localhost:9080/Jakarta-Library-1.0-SNAPSHOT/api/publishers/f8e63c10-5aaf-4b0d-a918-852c43855b4c
Content-Type: application/json

{
  "name": "testowy zmiana",
  "numOfWorkers": 2500
}

###

# Delete Publisher

DELETE http://localhost:9080/Jakarta-Library-1.0-SNAPSHOT/api/publishers/3b0a33fe-2d05-462c-bce7-032c0a542231